//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZ_MAAT._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassNamesToTPPCRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassNamesToTPPCRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayZ_MAAT._Core._Language._Stringtables.ClassNamesToTPPCRes", typeof(ClassNamesToTPPCRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konvertierung wurde abgebrochen! ähnelt.
        /// </summary>
        internal static string de_Canceled {
            get {
                return ResourceManager.GetString("de_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;TraderPlusPriceConfig.json&quot; ist bereits vorhanden. 
        ///
        ///Möchtest Du sie überschreiben? ähnelt.
        /// </summary>
        internal static string de_ExistingFile {
            get {
                return ResourceManager.GetString("de_ExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Datei definiert! ähnelt.
        /// </summary>
        internal static string de_LabelNoInput {
            get {
                return ResourceManager.GetString("de_LabelNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konvertierung wurde abgeschlossen! ähnelt.
        /// </summary>
        internal static string de_LabelStatusFinished {
            get {
                return ResourceManager.GetString("de_LabelStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Konvertiere Wert zu Kategorie  ähnelt.
        /// </summary>
        internal static string de_LogConvertCategory {
            get {
                return ResourceManager.GetString("de_LogConvertCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [ERROR] &lt;Fehler beim Konvertieren der Datei: ähnelt.
        /// </summary>
        internal static string de_LogConvertFatalError {
            get {
                return ResourceManager.GetString("de_LogConvertFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Konvertierung abgeschlossen.&gt; ähnelt.
        /// </summary>
        internal static string de_LogConvertFinish {
            get {
                return ResourceManager.GetString("de_LogConvertFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Konvertiere Zeile  ähnelt.
        /// </summary>
        internal static string de_LogConvertLine {
            get {
                return ResourceManager.GetString("de_LogConvertLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [WARN] &lt;Es wurde kein Kategorie-Eintrag (## oder //) gefunden. ClassNames werden der &apos;DummyCategory&apos; hinzugefügt! ähnelt.
        /// </summary>
        internal static string de_LogNoCategory {
            get {
                return ResourceManager.GetString("de_LogNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Keine Datei definiert.&gt; ähnelt.
        /// </summary>
        internal static string de_LogNoInput {
            get {
                return ResourceManager.GetString("de_LogNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Beginne Konvertierung....&gt;
        /// ähnelt.
        /// </summary>
        internal static string de_LogStartConvert {
            get {
                return ResourceManager.GetString("de_LogStartConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Anzahl konvertierter ClassNames:  ähnelt.
        /// </summary>
        internal static string de_LogTotal {
            get {
                return ResourceManager.GetString("de_LogTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The conversion was canceled! ähnelt.
        /// </summary>
        internal static string en_Canceled {
            get {
                return ResourceManager.GetString("en_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &quot;TraderPlusPriceConfig.json&quot; file already exists. 
        ///
        ///Would you like to overwrite it? ähnelt.
        /// </summary>
        internal static string en_ExistingFile {
            get {
                return ResourceManager.GetString("en_ExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No file defined! ähnelt.
        /// </summary>
        internal static string en_LabelNoInput {
            get {
                return ResourceManager.GetString("en_LabelNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conversion has been completed! ähnelt.
        /// </summary>
        internal static string en_LabelStatusFinished {
            get {
                return ResourceManager.GetString("en_LabelStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Convert value to category  ähnelt.
        /// </summary>
        internal static string en_LogConvertCategory {
            get {
                return ResourceManager.GetString("en_LogConvertCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [ERROR] &lt;Error while converting the file: ähnelt.
        /// </summary>
        internal static string en_LogConvertFatalError {
            get {
                return ResourceManager.GetString("en_LogConvertFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Conversion completed.&gt; ähnelt.
        /// </summary>
        internal static string en_LogConvertFinish {
            get {
                return ResourceManager.GetString("en_LogConvertFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Converting line  ähnelt.
        /// </summary>
        internal static string en_LogConvertLine {
            get {
                return ResourceManager.GetString("en_LogConvertLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [WARN] &lt;No category entry (## or //) was found. ClassNames are added to the &apos;DummyCategory&apos;! ähnelt.
        /// </summary>
        internal static string en_LogNoCategory {
            get {
                return ResourceManager.GetString("en_LogNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;No input file specified.&gt; ähnelt.
        /// </summary>
        internal static string en_LogNoInput {
            get {
                return ResourceManager.GetString("en_LogNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Start Converting....&gt;
        /// ähnelt.
        /// </summary>
        internal static string en_LogStartConvert {
            get {
                return ResourceManager.GetString("en_LogStartConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Total ClassNames converted: ähnelt.
        /// </summary>
        internal static string en_LogTotal {
            get {
                return ResourceManager.GetString("en_LogTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La conversion a été interrompue ! ähnelt.
        /// </summary>
        internal static string fr_Canceled {
            get {
                return ResourceManager.GetString("fr_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le fichier &quot;TraderPlusPriceConfig.json&quot; existe déjà. 
        ///
        ///Tu veux l&apos;écraser ? ähnelt.
        /// </summary>
        internal static string fr_ExistingFile {
            get {
                return ResourceManager.GetString("fr_ExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aucun fichier défini ! ähnelt.
        /// </summary>
        internal static string fr_LabelNoInput {
            get {
                return ResourceManager.GetString("fr_LabelNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La conversion est terminée ! ähnelt.
        /// </summary>
        internal static string fr_LabelStatusFinished {
            get {
                return ResourceManager.GetString("fr_LabelStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Convertir la valeur en catégorie  ähnelt.
        /// </summary>
        internal static string fr_LogConvertCategory {
            get {
                return ResourceManager.GetString("fr_LogConvertCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [ERREUR] &lt;Erreur lors de la conversion du fichier : ähnelt.
        /// </summary>
        internal static string fr_LogConvertFatalError {
            get {
                return ResourceManager.GetString("fr_LogConvertFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Conversion achevée&gt; ähnelt.
        /// </summary>
        internal static string fr_LogConvertFinish {
            get {
                return ResourceManager.GetString("fr_LogConvertFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Convertir la ligne  ähnelt.
        /// </summary>
        internal static string fr_LogConvertLine {
            get {
                return ResourceManager.GetString("fr_LogConvertLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [WARN] &lt;Aucune entrée de catégorie (## ou //) n&apos;a été trouvée. Les ClassNames sont ajoutés à la &apos;DummyCategory&apos; ! ähnelt.
        /// </summary>
        internal static string fr_LogNoCategory {
            get {
                return ResourceManager.GetString("fr_LogNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Aucun fichier d&apos;entrée n&apos;a été spécifié.&gt; ähnelt.
        /// </summary>
        internal static string fr_LogNoInput {
            get {
                return ResourceManager.GetString("fr_LogNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Démarrer la conversion....&gt;
        /// ähnelt.
        /// </summary>
        internal static string fr_LogStartConvert {
            get {
                return ResourceManager.GetString("fr_LogStartConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [INFO] &lt;Total des ClassNames converties : ähnelt.
        /// </summary>
        internal static string fr_LogTotal {
            get {
                return ResourceManager.GetString("fr_LogTotal", resourceCulture);
            }
        }
    }
}
