//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZ_MAAT._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExtractFromTypesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtractFromTypesRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayZ_MAAT._Core._Language._Stringtables.ExtractFromTypesRes", typeof(ExtractFromTypesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Extraktion wurde abgebrochen! ähnelt.
        /// </summary>
        internal static string de_Canceled {
            get {
                return ResourceManager.GetString("de_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ## ← dies oder 
        ///// ← das verwenden 
        ///// ← um Kategorien zu erstellen, während
        ///## ← Konvertierung zu TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string de_CategoryHint {
            get {
                return ResourceManager.GetString("de_CategoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ClassNames exportiert nach:  ähnelt.
        /// </summary>
        internal static string de_ClassNamePath {
            get {
                return ResourceManager.GetString("de_ClassNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei ClassNames.txt ist bereits vorhanden. 
        ///
        ///Möchtest Du sie überschreiben? ähnelt.
        /// </summary>
        internal static string de_ExistingFile {
            get {
                return ResourceManager.GetString("de_ExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML-Parsing fehlgeschlagen: ähnelt.
        /// </summary>
        internal static string de_ParserError {
            get {
                return ResourceManager.GetString("de_ParserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML-Parsing fehlgeschlagen! Überprüfe die Fehlermeldung und versuche es erneut! ähnelt.
        /// </summary>
        internal static string de_ParserError1 {
            get {
                return ResourceManager.GetString("de_ParserError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extraction canceled! ähnelt.
        /// </summary>
        internal static string en_Canceled {
            get {
                return ResourceManager.GetString("en_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use ## or // at the beginning of a line to create a category for the TraderPlusPriceConfig. 
        ///Categories are then created from this when converting! ähnelt.
        /// </summary>
        internal static string en_CategoryHint {
            get {
                return ResourceManager.GetString("en_CategoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ClassNames exported to:  ähnelt.
        /// </summary>
        internal static string en_ClassNamePath {
            get {
                return ResourceManager.GetString("en_ClassNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt file already exists. 
        ///
        ///Would you like to overwrite it? ähnelt.
        /// </summary>
        internal static string en_ExistingFile {
            get {
                return ResourceManager.GetString("en_ExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML-Parsing failed:  ähnelt.
        /// </summary>
        internal static string en_ParserError {
            get {
                return ResourceManager.GetString("en_ParserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML-Parsing failed! Check the Error-Message and try again! ähnelt.
        /// </summary>
        internal static string en_ParserError1 {
            get {
                return ResourceManager.GetString("en_ParserError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extraction annulée ! ähnelt.
        /// </summary>
        internal static string fr_Canceled {
            get {
                return ResourceManager.GetString("fr_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ## ← utiliser ceci 
        ///// ← ou ça
        ///// ← pour créer des catégories tout en
        ///## ← convertir en TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string fr_CategoryHint {
            get {
                return ResourceManager.GetString("fr_CategoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Noms de classe exportés vers :  ähnelt.
        /// </summary>
        internal static string fr_ClassNamePath {
            get {
                return ResourceManager.GetString("fr_ClassNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le fichier ClassNames.txt existe déjà. 
        ///
        ///Souhaitez-vous l&apos;écraser ? ähnelt.
        /// </summary>
        internal static string fr_ExistingFile {
            get {
                return ResourceManager.GetString("fr_ExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Échec de l&apos;analyse XML :  ähnelt.
        /// </summary>
        internal static string fr_ParserError {
            get {
                return ResourceManager.GetString("fr_ParserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die L&apos;analyse XML a échoué ! Vérifiez le message d&apos;erreur et réessayez ! ähnelt.
        /// </summary>
        internal static string fr_ParserError1 {
            get {
                return ResourceManager.GetString("fr_ParserError1", resourceCulture);
            }
        }
    }
}
