//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZ_MAAT._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayZ_MAAT._Core._Language._Stringtables.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browser konnte nicht gestartet werden! ähnelt.
        /// </summary>
        internal static string de_BrowserError {
            get {
                return ResourceManager.GetString("de_BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt → TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string de_Button_ConvertClassNameToTraderPlusPriceConfig {
            get {
                return ResourceManager.GetString("de_Button_ConvertClassNameToTraderPlusPriceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt → types.xml ähnelt.
        /// </summary>
        internal static string de_Button_ConvertClassToType {
            get {
                return ResourceManager.GetString("de_Button_ConvertClassToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TraderPlusVehicleConfig.json → spawnabletypes.xml ähnelt.
        /// </summary>
        internal static string de_Button_ConvertTPVCToSpawnabletypes {
            get {
                return ResourceManager.GetString("de_Button_ConvertTPVCToSpawnabletypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt aus config.cpp extrahieren ähnelt.
        /// </summary>
        internal static string de_Button_ExtractCpp {
            get {
                return ResourceManager.GetString("de_Button_ExtractCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt aus types.xml extrahieren ähnelt.
        /// </summary>
        internal static string de_Button_ExtractFromTypes {
            get {
                return ResourceManager.GetString("de_Button_ExtractFromTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dr.Jones Trader.txt → TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string de_Button_TraderConverter {
            get {
                return ResourceManager.GetString("de_Button_TraderConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validierung und Verschönerung von XML oder JSON ähnelt.
        /// </summary>
        internal static string de_Button_Validate {
            get {
                return ResourceManager.GetString("de_Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TraderPlusPriceConfig.json validieren ähnelt.
        /// </summary>
        internal static string de_Button_VerifyTPPriceCfg {
            get {
                return ResourceManager.GetString("de_Button_VerifyTPPriceCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Extrahieren der ClassNames: ähnelt.
        /// </summary>
        internal static string de_ExtractClassTypesError {
            get {
                return ResourceManager.GetString("de_ExtractClassTypesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konverter ähnelt.
        /// </summary>
        internal static string de_GroupBox_Converter {
            get {
                return ResourceManager.GetString("de_GroupBox_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extraktor ähnelt.
        /// </summary>
        internal static string de_GroupBox_Extractor {
            get {
                return ResourceManager.GetString("de_GroupBox_Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validierer ähnelt.
        /// </summary>
        internal static string de_GroupBox_Validator {
            get {
                return ResourceManager.GetString("de_GroupBox_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte warten... ähnelt.
        /// </summary>
        internal static string de_Label_Working {
            get {
                return ResourceManager.GetString("de_Label_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Überprüfen der Konfigurationsdatei: ähnelt.
        /// </summary>
        internal static string de_TPValidError {
            get {
                return ResourceManager.GetString("de_TPValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Konvertieren der Datei: ähnelt.
        /// </summary>
        internal static string de_TraderConvertError {
            get {
                return ResourceManager.GetString("de_TraderConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Überprüfen der Datei: ähnelt.
        /// </summary>
        internal static string de_ValidateError {
            get {
                return ResourceManager.GetString("de_ValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browser could not be started! ähnelt.
        /// </summary>
        internal static string en_BrowserError {
            get {
                return ResourceManager.GetString("en_BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt → TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string en_Button_ConvertClassNameToTraderPlusPriceConfig {
            get {
                return ResourceManager.GetString("en_Button_ConvertClassNameToTraderPlusPriceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt → types.xml ähnelt.
        /// </summary>
        internal static string en_Button_ConvertClassToType {
            get {
                return ResourceManager.GetString("en_Button_ConvertClassToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TraderPlusVehicleConfig.json → spawnabletypes.xml ähnelt.
        /// </summary>
        internal static string en_Button_ConvertTPVCToSpawnabletypes {
            get {
                return ResourceManager.GetString("en_Button_ConvertTPVCToSpawnabletypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extract ClassNames.txt from config.cpp ähnelt.
        /// </summary>
        internal static string en_Button_ExtractCpp {
            get {
                return ResourceManager.GetString("en_Button_ExtractCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extract ClassNames.txt from types.xml ähnelt.
        /// </summary>
        internal static string en_Button_ExtractFromTypes {
            get {
                return ResourceManager.GetString("en_Button_ExtractFromTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dr.Jones Trader.txt → TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string en_Button_TraderConverter {
            get {
                return ResourceManager.GetString("en_Button_TraderConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validate &amp; Beautify XML or JSON ähnelt.
        /// </summary>
        internal static string en_Button_Validate {
            get {
                return ResourceManager.GetString("en_Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validate TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string en_Button_VerifyTPPriceCfg {
            get {
                return ResourceManager.GetString("en_Button_VerifyTPPriceCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error when extracting the ClassNames:  ähnelt.
        /// </summary>
        internal static string en_ExtractClassTypesError {
            get {
                return ResourceManager.GetString("en_ExtractClassTypesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Converter ähnelt.
        /// </summary>
        internal static string en_GroupBox_Converter {
            get {
                return ResourceManager.GetString("en_GroupBox_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extractor ähnelt.
        /// </summary>
        internal static string en_GroupBox_Extractor {
            get {
                return ResourceManager.GetString("en_GroupBox_Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validator ähnelt.
        /// </summary>
        internal static string en_GroupBox_Validator {
            get {
                return ResourceManager.GetString("en_GroupBox_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait... ähnelt.
        /// </summary>
        internal static string en_Label_Working {
            get {
                return ResourceManager.GetString("en_Label_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error when checking the configuration file:  ähnelt.
        /// </summary>
        internal static string en_TPValidError {
            get {
                return ResourceManager.GetString("en_TPValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error converting the file:  ähnelt.
        /// </summary>
        internal static string en_TraderConvertError {
            get {
                return ResourceManager.GetString("en_TraderConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while checking the file:  ähnelt.
        /// </summary>
        internal static string en_ValidateError {
            get {
                return ResourceManager.GetString("en_ValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le navigateur n&apos;a pas pu être démarré ! ähnelt.
        /// </summary>
        internal static string fr_BrowserError {
            get {
                return ResourceManager.GetString("fr_BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt → TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string fr_Button_ConvertClassNameToTraderPlusPriceConfig {
            get {
                return ResourceManager.GetString("fr_Button_ConvertClassNameToTraderPlusPriceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClassNames.txt → types.xml ähnelt.
        /// </summary>
        internal static string fr_Button_ConvertClassToType {
            get {
                return ResourceManager.GetString("fr_Button_ConvertClassToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TraderPlusVehicleConfig.json → spawnabletypes.xml ähnelt.
        /// </summary>
        internal static string fr_Button_ConvertTPVCToSpawnabletypes {
            get {
                return ResourceManager.GetString("fr_Button_ConvertTPVCToSpawnabletypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extraire ClassNames.txt de config.cpp ähnelt.
        /// </summary>
        internal static string fr_Button_ExtractCpp {
            get {
                return ResourceManager.GetString("fr_Button_ExtractCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extraire ClassNames.txt de types.xml ähnelt.
        /// </summary>
        internal static string fr_Button_ExtractFromTypes {
            get {
                return ResourceManager.GetString("fr_Button_ExtractFromTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dr.Jones Trader.txt → TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string fr_Button_TraderConverter {
            get {
                return ResourceManager.GetString("fr_Button_TraderConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valider et embellir XML ou JSON ähnelt.
        /// </summary>
        internal static string fr_Button_Validate {
            get {
                return ResourceManager.GetString("fr_Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valider TraderPlusPriceConfig.json ähnelt.
        /// </summary>
        internal static string fr_Button_VerifyTPPriceCfg {
            get {
                return ResourceManager.GetString("fr_Button_VerifyTPPriceCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur lors de l&apos;extraction des ClassNames :  ähnelt.
        /// </summary>
        internal static string fr_ExtractClassTypesError {
            get {
                return ResourceManager.GetString("fr_ExtractClassTypesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convertisseur ähnelt.
        /// </summary>
        internal static string fr_GroupBox_Converter {
            get {
                return ResourceManager.GetString("fr_GroupBox_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extracteur ähnelt.
        /// </summary>
        internal static string fr_GroupBox_Extractor {
            get {
                return ResourceManager.GetString("fr_GroupBox_Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valideur ähnelt.
        /// </summary>
        internal static string fr_GroupBox_Validator {
            get {
                return ResourceManager.GetString("fr_GroupBox_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veuillez patienter... ähnelt.
        /// </summary>
        internal static string fr_Label_Working {
            get {
                return ResourceManager.GetString("fr_Label_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur lors de la vérification du fichier de configuration :  ähnelt.
        /// </summary>
        internal static string fr_TPValidError {
            get {
                return ResourceManager.GetString("fr_TPValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur lors de la conversion du fichier :  ähnelt.
        /// </summary>
        internal static string fr_TraderConvertError {
            get {
                return ResourceManager.GetString("fr_TraderConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur lors de la vérification du fichier :  ähnelt.
        /// </summary>
        internal static string fr_ValidateError {
            get {
                return ResourceManager.GetString("fr_ValidateError", resourceCulture);
            }
        }
    }
}
