//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZ_MAAT._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayZ_MAAT._Core._Language._Stringtables.MessageForm", typeof(MessageForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string de_ButtonNo {
            get {
                return ResourceManager.GetString("de_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        internal static string de_ButtonOk {
            get {
                return ResourceManager.GetString("de_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string de_ButtonYes {
            get {
                return ResourceManager.GetString("de_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler! ähnelt.
        /// </summary>
        internal static string de_TitleError {
            get {
                return ResourceManager.GetString("de_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frage ähnelt.
        /// </summary>
        internal static string de_TitleQuestion {
            get {
                return ResourceManager.GetString("de_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung! ähnelt.
        /// </summary>
        internal static string de_TitleWarning {
            get {
                return ResourceManager.GetString("de_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string en_ButtonNo {
            get {
                return ResourceManager.GetString("en_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        internal static string en_ButtonOk {
            get {
                return ResourceManager.GetString("en_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string en_ButtonYes {
            get {
                return ResourceManager.GetString("en_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string en_TitleError {
            get {
                return ResourceManager.GetString("en_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string en_TitleQuestion {
            get {
                return ResourceManager.GetString("en_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning! ähnelt.
        /// </summary>
        internal static string en_TitleWarning {
            get {
                return ResourceManager.GetString("en_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Non ähnelt.
        /// </summary>
        internal static string fr_ButtonNo {
            get {
                return ResourceManager.GetString("fr_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        internal static string fr_ButtonOk {
            get {
                return ResourceManager.GetString("fr_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oui ähnelt.
        /// </summary>
        internal static string fr_ButtonYes {
            get {
                return ResourceManager.GetString("fr_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur ! ähnelt.
        /// </summary>
        internal static string fr_TitleError {
            get {
                return ResourceManager.GetString("fr_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string fr_TitleQuestion {
            get {
                return ResourceManager.GetString("fr_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attention ! ähnelt.
        /// </summary>
        internal static string fr_TitleWarning {
            get {
                return ResourceManager.GetString("fr_TitleWarning", resourceCulture);
            }
        }
    }
}
