//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZ_MAAT._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayZ_MAAT._Core._Language._Stringtables.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen erfolgreich gespeichert! ähnelt.
        /// </summary>
        internal static string de_SettingsSaved {
            get {
                return ResourceManager.GetString("de_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DayZ M.A.A.T. wurde erfolgreich gestartet ähnelt.
        /// </summary>
        internal static string de_Startup {
            get {
                return ResourceManager.GetString("de_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Validierung der TraderPlusPriceConfig.json ist fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string de_TPVerifFail {
            get {
                return ResourceManager.GetString("de_TPVerifFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Validierung der TraderPlusPriceConfig.json wurde ohne Fehler abgeschlossen. ähnelt.
        /// </summary>
        internal static string de_TPVerifSuccess {
            get {
                return ResourceManager.GetString("de_TPVerifSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings saved successfully! ähnelt.
        /// </summary>
        internal static string en_SettingsSaved {
            get {
                return ResourceManager.GetString("en_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DayZ M.A.A.T. has been successfully launched ähnelt.
        /// </summary>
        internal static string en_Startup {
            get {
                return ResourceManager.GetString("en_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The validation of the TraderPlusPriceConfig.json failed! ähnelt.
        /// </summary>
        internal static string en_TPVerifFail {
            get {
                return ResourceManager.GetString("en_TPVerifFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The validation of the TraderPlusPriceConfig.json was completed without errors. ähnelt.
        /// </summary>
        internal static string en_TPVerifSuccess {
            get {
                return ResourceManager.GetString("en_TPVerifSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paramètres enregistrés avec succès ! ähnelt.
        /// </summary>
        internal static string fr_SettingsSaved {
            get {
                return ResourceManager.GetString("fr_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DayZ M.A.A.T. a été lancé avec succès ähnelt.
        /// </summary>
        internal static string fr_Startup {
            get {
                return ResourceManager.GetString("fr_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La validation du fichier TraderPlusPriceConfig.json a échoué ! ähnelt.
        /// </summary>
        internal static string fr_TPVerifFail {
            get {
                return ResourceManager.GetString("fr_TPVerifFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La validation du fichier TraderPlusPriceConfig.json s&apos;est terminée sans erreur. ähnelt.
        /// </summary>
        internal static string fr_TPVerifSuccess {
            get {
                return ResourceManager.GetString("fr_TPVerifSuccess", resourceCulture);
            }
        }
    }
}
